rule outputs_all:
    input:
        graph_country_bids_price = "out/graph_country_bids_price.html",
        graph_price_auction = "out/hist_price_auction.png",
        graph_price_storage = "out/hist_price_storage.png",
        graph_price = "out/hist_price.png",
        graph_map = "out/world_map.html",
        summary_stats = "out/summary_stats.html",
        webpage_timestamp = "out/gh_publication_date_ddmmyy.txt"

rule scrape_data:
    conda: "envs/env.yaml"
    input:
        script = "src/scrape_data.py",
        #data = "data/clean/data_clean.csv"
    output:
        path = "data"
    shell:
        'python {input.script} --output_path {output.path}'
